### PR TITLE
Update examples & tests to align with YosemitechModbus

### PR DESCRIPTION
**Pull request by aufdenkampe**
by following recent EnviroDIY conventions for formatting, default values (i.e. serial baud), and our latest modbus adpaters that separately switch power to the sensor. @hodsonm-cws

### CODE REVIEW

**Comment by aufdenkampe** [comment]
@hodsonm-cws, can you confirm whether these new files in the `develop` branch work for you?

**Comment by hodsonm-cws** [comment]
I now get:

.pio\libdeps\mayfly\EnviroDIY_ModularSensors\src\sensors\KellerParent.cpp: In member function 'virtual bool KellerParent::setup()':
.pio\libdeps\mayfly\EnviroDIY_ModularSensors\src\sensors\KellerParent.cpp:66:5: error: 'sensor' was not declared in this scope

**Comment by SRGDamia1** [comment]
Is this ready to go?

**Comment by aufdenkampe** [comment]
@SRGDamia1, I’m quite confident that these new sketches will work, given that:
1. They don't add or change any functionality but rather focus on adding code comments and additional printouts to the serial monitor.
2. The changes were basically copied from updates I made to the [YosemitechModbus](https://github.com/EnviroDIY/YosemitechModbus) and [GroPointModbus](https://github.com/EnviroDIY/GroPointModbus) libraries.

**Pull request merged**
